# must be unique in a given SonarQube Server instance
sonar.projectKey=pipes-ci
sonar.projectName=pipes-ci
sonar.projectBaseDir=/home/pablofranca/Documents/Universidade/4o semestre/Arquitetura de Software/Atividades de casa/pipes_and_filters
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to 'not provided'
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .encoding
sonar.sourceEncoding=UTF-8
#sonar.sources=.

# Encoding of the source code. Default is default system